# Site settings
title: MeltingWaldo
owner: Waldo
description: > 
  We have a couple of iOS 500 applications - Play500 and Score500. Enjoy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.meltingwaldo.com" # the base hostname & protocol for your site
twitter_username: meltingwaldo
github_username:  waldo

# Build settings
markdown: kramdown
